# Generated by Django 5.2 on 2025-04-22 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_musclegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FastingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('planned_duration', models.PositiveIntegerField(help_text='Planned fasting duration in hours')),
                ('protocol', models.CharField(choices=[('16_8', '16:8 (Leangains)'), ('18_6', '18:6'), ('20_4', '20:4 (Warrior Diet)'), ('5_2', '5:2 (5 normal days, 2 fasting days)'), ('custom', 'Custom')], default='16_8', max_length=10)),
                ('custom_hours', models.PositiveIntegerField(blank=True, help_text='For custom protocol, hours to fast', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
